### PR TITLE
improve coverage of sheet names with wild character encoding

### PR DESCRIPTION
**Pull request by katossky**
a dependence to `stringi` is introduced, but it greatly improves string comparisons

### CODE REVIEW

**Comment by katossky** [comment]
Maybe some tests should be added? The bug is mentioned in issue #32 .

**Comment by chainsawriot** [comment]
Thank you a lot for the commit!  It will be great if you can provide at least one test for this. If you don't know how to create a `testthat` unit test, would you please provide an ODS file with wild characters sheet name?

**Comment by katossky** [comment]
I try to to create a `testhat` test later today. I must learn ;)
I just upload an empty file, with 2 sheets, right?

**Comment by katossky** [comment]
I was also thinking maybe the issue has to come back to `xml2` package, since this package should not send back poorly-encoded strings in the first place...

**Comment by katossky** [comment]
I guess we're good now.

**Comment by katossky** [comment]
(I had trouble trying to reproduce the bug in a consistent way. Could not find the reason why sometimes I get the bug, sometimes not. I actually included a reduced version of the original file I found the bug in, since it is the only one with which the bug is steady... I must have copy-pasted this weird `é` from somewhere.)

**Pull request merged**
